out_dir: "../../../out/models"
seed: False
num_replicates: 1
trn_offset: 1.0
tst_val_offset: 1.0
epochs: 100
hidden_size: 10
dropout: 0.2
recurrent_dropout: 0.2
finetune_learning_rate: 0.01
early_stopping: False
val_sites:
  - "01472104"
  - "01473500"
  - "01481500"
test_sites:
  - "01475530"
  - "01475548"
train_start_date: '1980-01-01'
train_end_date: '2014-10-01'
val_start_date: '2014-10-01'
val_end_date: '2015-10-01'
test_start_date: '2015-10-01'
test_end_date: '2022-10-01'
 
