exp_name: "0_baseline_LSTM"
x_vars:
  - "pr"
  - "SLOPE"
  - "tmmx"
  - "tmmn"
  - "srad"
  - "CAT_BASIN_SLOPE"
  - "CAT_ELEV_MEAN"
  - "CAT_BASIN_AREA"
  - "CAT_IMPV11"
  - "CAT_CNPY11_BUFF100"
  - "CAT_TWI"
y_vars:
  - "do_min"
  - "do_mean"
  - "do_max"
lambdas:
  - 1
  - 1
  - 1
 
