exp_name: "0_baseline_LSTM"

site_set: "well_obs"

#x_vars: ['seg_ccov', 'seg_rain', 'seg_slope', 'seg_tave_air', 'seginc_swrad', 'hru_slope', 'hru_aspect', 'hru_elev', 'hru_area', 'hru_percent_imperv', 'covden_sum', 'covden_win', 'soil_moist_max']

x_vars: ['CAT_CNPY11_BUFF100','pr','SLOPE','tmmx','srad','CAT_BASIN_SLOPE','CAT_BASIN_AREA','CAT_IMPV11']

y_vars: ['do_min', 'do_mean', 'do_max']

lambdas: [1, 1, 1]

